name: Push

on:
  push:
    branches:
      - main

env:
  # TODO: Change variable to your registry
  REGISTRY_NAME: hexletbasics

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          docker-compose --file docker-compose.test.yml build
          docker-compose --file docker-compose.test.yml run sut

      - name: Set repository name
        run: |
          echo "REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')" >> $GITHUB_ENV

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push into docker hub
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.REGISTRY_NAME }}/${{ env.REPOSITORY_NAME }}:latest

      # - name: Send notification into Slack
      #   if: ${{ always() }}
      #   uses: rtCamp/action-slack-notify@v2.0.0
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
